"""Add UserPreference model

Revision ID: 0e3582eaad92
Revises: 08f8405ef96d
Create Date: 2025-04-22 16:23:29.369273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3582eaad92'
down_revision = '08f8405ef96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('job_results', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('resume_analysis', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('projects',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('experience',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('experience_years',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('suggested_roles',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('resume_filename',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('resume_filename',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    with op.batch_alter_table('resume_analysis', schema=None) as batch_op:
        batch_op.alter_column('suggested_roles',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('experience_years',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('experience',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('projects',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('skills',
               existing_type=sa.TEXT(),
               nullable=True)

    op.drop_table('user_preference')
    # ### end Alembic commands ###
